// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUD6vU6z6DqztnZnopdN5bdHo4WVuHCDI',
    appId: '1:834985001119:web:c144fde5341bd0b04322aa',
    messagingSenderId: '834985001119',
    projectId: 'kycflutter-7cd11',
    authDomain: 'kycflutter-7cd11.firebaseapp.com',
    storageBucket: 'kycflutter-7cd11.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_Hpd0jmjZ8wskNJywSqoVehcN9VFOvw0',
    appId: '1:834985001119:android:7bea30f52d4165fb4322aa',
    messagingSenderId: '834985001119',
    projectId: 'kycflutter-7cd11',
    storageBucket: 'kycflutter-7cd11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsJamqHpGM_CJspYek7OVUNynLggXWczQ',
    appId: '1:834985001119:ios:102256ee1255846a4322aa',
    messagingSenderId: '834985001119',
    projectId: 'kycflutter-7cd11',
    storageBucket: 'kycflutter-7cd11.firebasestorage.app',
    iosBundleId: 'com.mostafa.kyc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsJamqHpGM_CJspYek7OVUNynLggXWczQ',
    appId: '1:834985001119:ios:102256ee1255846a4322aa',
    messagingSenderId: '834985001119',
    projectId: 'kycflutter-7cd11',
    storageBucket: 'kycflutter-7cd11.firebasestorage.app',
    iosBundleId: 'com.mostafa.kyc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUD6vU6z6DqztnZnopdN5bdHo4WVuHCDI',
    appId: '1:834985001119:web:8a991297766866ca4322aa',
    messagingSenderId: '834985001119',
    projectId: 'kycflutter-7cd11',
    authDomain: 'kycflutter-7cd11.firebaseapp.com',
    storageBucket: 'kycflutter-7cd11.firebasestorage.app',
  );
}
