// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVftpWnDVi7dd8ITAKX-ppY4a3SNupwC4',
    appId: '1:621727622320:web:52a8d7183f40e4b2e18775',
    messagingSenderId: '621727622320',
    projectId: 'newkycapp',
    authDomain: 'newkycapp.firebaseapp.com',
    storageBucket: 'newkycapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMVO-4QttLeu698AkQnQ7964Ne_PxWnkc',
    appId: '1:621727622320:android:8d14b823cad7edc5e18775',
    messagingSenderId: '621727622320',
    projectId: 'newkycapp',
    storageBucket: 'newkycapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA97sHRvoP4cT0bJ97J2E74W4fSQJlZIMQ',
    appId: '1:621727622320:ios:1108cb89225ece3ee18775',
    messagingSenderId: '621727622320',
    projectId: 'newkycapp',
    storageBucket: 'newkycapp.firebasestorage.app',
    iosBundleId: 'com.mostafa.kyc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA97sHRvoP4cT0bJ97J2E74W4fSQJlZIMQ',
    appId: '1:621727622320:ios:1108cb89225ece3ee18775',
    messagingSenderId: '621727622320',
    projectId: 'newkycapp',
    storageBucket: 'newkycapp.firebasestorage.app',
    iosBundleId: 'com.mostafa.kyc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVftpWnDVi7dd8ITAKX-ppY4a3SNupwC4',
    appId: '1:621727622320:web:334333e967722899e18775',
    messagingSenderId: '621727622320',
    projectId: 'newkycapp',
    authDomain: 'newkycapp.firebaseapp.com',
    storageBucket: 'newkycapp.firebasestorage.app',
  );
}
